# print "Configuring PATH..."

# Set PATH properly
export PATH="$HOME/bin:$PATH"
# export PATH="$HOME/bin/roslyn:$PATH"
export PATH="$HOME/Library/Python/3.9/bin:$PATH"
export PATH="$HOME/.lmstudio/bin:$PATH"
export PATH="/usr/local/opt/postgresql@17/bin:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
export PATH="$DOTFILES/bin:$PATH"
export PATH="$DOTFILES/bin/bash:$PATH"
export PATH="$DOTFILES/bin/python:$PATH"
export PATH="$DOTFILES/bin/python/bash:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/Users/nolanmiller/.matter/bin:$PATH"
export PATH="$PATH:/Users/nolanmiller/.dotnet/tools"
